language: php
sudo: false
dist: trusty

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_TRAVISCI="travis:phpunit"

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.9.11
    - php: 5.6
      env: WP_VERSION=latest

before_install:
  - travis_retry composer self-update

install:
  - composer install --prefer-source --no-interaction --dev
  - composer global require "phpunit/phpunit=^5"

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install --no-progress
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

script:
  - composer run-phpcs

notifications:
  on_success: never
  on_failure: always
